### ISSUE TITLE
Integration with tracy_client

### ISSUE THREAD

**Issue by cwfitzgerald** [Wumpf/wgpu-profiler#15]
Now that tracy has proper C api support for GPU timestamps, it would be a great extension to this library to offer a tracy feature where the timestamps collected by wgpu-profiler are reported to tracy.

I am planning on working on this in **a while** but I wanted to clear it with you before I did.

**Comment by Imberflur** [comment]
This would be very useful IMO. I assume this will involve addressing the implementation in `tracy_client` first https://github.com/nagisa/rust_tracy_client/issues/19?

**Comment by cwfitzgerald** [comment]
We shouldn't have to. That is basically an implementation of vulkan query set management like wgpu-profiler does. We just would need to build a simple rust interface to the __tracy_emit_gpu* functions in tracy_client and then bind to that from here.

Just depends on https://github.com/nagisa/rust_tracy_client/issues/39 (which I see you've already saw)

I actually think I might hack on this tomorrow.

**Comment by Imberflur** [comment]
>  We just would need to build a simple rust interface to the __tracy_emit_gpu* functions in tracy_client and then bind to that from here.

Oh, I assumed this is what the issue I linked meant (i.e. exposing this simple interface at the tracy_client level).

**Comment by cwfitzgerald** [comment]
Yeah that issue is for the actual implementation on top of vulkan, like tracy has natively for all the apis.
