### ISSUE TITLE
Slight docs inaccuracy

### ISSUE THREAD

**Issue by Imberflur** [Wumpf/wgpu-profiler#2]
`/// timestamp_period: Result of wgpu::Queue::get_timestamp_period()`
This is a method on the [`Adapter`](https://docs.rs/wgpu/0.7.0/wgpu/struct.Adapter.html#method.get_timestamp_period)

**Comment by Imberflur** [comment]
nvm this is changed to the `Queue` in wgpu master

**Comment by Wumpf** [comment]
I was working from wgpu master, but the crate implies that it should work with 0.7
So that's still a legit bug then :)
