### ISSUE TITLE
Broken wasm build due to std::process::id function call, is this a bug?

### ISSUE THREAD

**Issue by Davidster** [Wumpf/wgpu-profiler#61]
WASM build is broken in my project since upgrading wgpu-profiler. I guess it's been 'broken' since https://github.com/Wumpf/wgpu-profiler/pull/30. 

I'm not sure how you would like to proceed with this. On the one hand, I could probably find a way to never call wgpu-profiler functions from wasm builds. On the other hand, it was pretty nice being able to compile to web with no extra work required.

What do you think?

**Comment by Wumpf** [comment]
oof yeah definitely a bug. Should:
* add wasm build to ci
* make pid gathering native-only
